build = "mvn clean install -f cohort-parent/pom.xml"
jdkVersion = "8"

tools = ["open source vulnerabilities", "shellcheck"]
ignoreRules = ["SC1128", "The shebang must be on the first line. Delete blanks and move comments."]
