{
 "title": "Quality Measure and Cohort Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_ID", "label": "Spark Application Id", "query": { "query": "label_values(application_id)" } }
  ]
 },
 "panels": [
  { "title": "Cohort Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Context Evaluation in Progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_plugin_com_ibm_cohort_cql_spark_metrics_CustomMetricSparkPlugin_Cohort_CurrentlyEvaluatingContext_Value"
    }
   ]
  },
  {
   "title": "Contexts Completed Processing",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_plugin_com_ibm_cohort_cql_spark_metrics_CustomMetricSparkPlugin_Cohort_ContextAccum_Number",
     "legendFormat": "processed"
    },
    {
     "expr": "metrics_spark_${application_ID}_driver_plugin_com_ibm_cohort_cql_spark_CustomMetricSparkPlugin_metrics_CohortMetricCounter_Count",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CQL Evaluations Completed per Context",
   "type": "graph",
   "description": "uses the perContextAccum accumulator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_plugin_com_ibm_cohort_cql_spark_metrics_CustomMetricSparkPlugin_Cohort_PerContextAccum_Number"
    }
   ]
  },
  {
   "title": "Used On Heap Memory in bytes",
   "type": "graph",
   "description": "Used on heap memory currently for storage, in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_usedOnHeapStorageMemory_bytes{application_id=\"spark-${application_ID}\"}"
    }
   ]
  },
  {
   "title": "Spark Job, Stage, and Task Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Active/Total Spark Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_DAGScheduler_job_activeJobs_Number"
    },
    {
     "expr": "metrics_spark_${application_ID}_driver_DAGScheduler_job_allJobs_Number"
    }
   ]
  },
  {
   "title": "Succeeded/Failed Spark Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_appStatus_jobs_succeededJobs_Count"
    },
    {
     "expr": "metrics_spark_${application_ID}_driver_appStatus_jobs_failedJobs_Count"
    }
   ]
  },
  {
   "title": "Running/Waiting Spark Stages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_DAGScheduler_stage_runningStages_Number"
    },
    {
     "expr": "metrics_spark_${application_ID}_driver_DAGScheduler_stage_waitingStages_Number"
    }
   ]
  },
  {
   "title": "Completed/Failed Spark Stages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_spark_${application_ID}_driver_appStatus_stages_completedStages_Count"
    },
    {
     "expr": "metrics_spark_${application_ID}_driver_appStatus_stages_failedStages_Count"
    }
   ]
  },
  {
   "title": "Active Spark Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_activeTasks{application_id=\"spark-${application_ID}\", executor_id!~\".*driver.*\"}"
    }
   ]
  },
  {
   "title": "Completed/Total Spark Tasks per Executor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_completedTasks_total{application_id=\"spark-${application_ID}\", executor_id!~\".*driver.*\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "metrics_executor_totalTasks_total{application_id=\"spark-${application_ID}\", executor_id!~\".*driver.*\"}"
    }
   ]
  }
 ]
}