# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
annotations:
  TOOLCHAIN_ID: null
  GIT_URL: null
  GIT_BRANCH: null
  GIT_COMMIT: null
  USER_NAME: null
  APPLICATION_VERSION: null

image:
#  repository: registry.ng.bluemix.net
  repository: us.icr.io
#  tag: daily-100
  tag: v1
  pullPolicy: Always
#  namespace: cdt-oncology-wocs-rns
  namespace: cdt-provider-cohort-rns
#  namespaceForKube: cdt-oncology-wora-ns-01
  namespaceForKube: dev
#  imageName: wora-solution-1.0.0
  imageName: cohort-app
  #pullSecret: default-us-icr-io
  pullSecret: all-icr-io

#nameOverride: "wora"
nameOverride: "cohort"
DEBUG_FAILURE: false

service:
  type: ClusterIP
  apiservicePortSecure: 9443
  ports:
    - 9080
    - 9443

wora:
  woraUser: 1025
  tenantId: TENANT_ID
  # the correct unit abbreviation below is Gi
  #memory: "16Gi"
  memory: "2Gi"
woraReplacementTokens:
  # the correct unit abbreviation below is g
  #MIN_HEAP_TOKEN: "8g"
  MIN_HEAP_TOKEN: "1g"
  #MAX_HEAP_TOKEN: "12g"
  MAX_HEAP_TOKEN: "2g"
  LOG_PHI_DIR_TOKEN: "/var/log/apps/wora"
  LOG_NOPHI_DIR_TOKEN: "/var/log/apps/wora"
  ENABLED_DARK_FEATURES_TOKEN: none
  PATIENT_PROCESSING_THREADS_TOKEN: 10
  MAXLOG_FILES_TOKEN: 20
  TRACE_SPEC_TOKEN: "*=info"
  CONTEXT_ROOT_TOKEN: "wh-wora/001/ra"
  HTTP_PORT_TOKEN: -1
  PDM_URL_TOKEN: wh-pdm-dev.us-south.wh-pdm.dev.watson-health.ibm.com:9443/pdm-dev/FROM_VALUES/api/v1/