#
# (C) Copyright IBM Corp. 2021, 2021
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
annotations:
  TOOLCHAIN_ID: null
  GIT_URL: null
  GIT_BRANCH: null
  GIT_COMMIT: null
  USER_NAME: null
  APPLICATION_VERSION: null

image:
  repository: <helm-repo>
  tag: <helm-tag>
  pullSecret: regsecret
  pullPolicy: IfNotPresent
  imageName: cohort-app

DEBUG_FAILURE: false

service:
  type: ClusterIP
  externalPort: 9443
  ports:
    - 9080
    - 9443

internalTlsCertSecretName: cohort-services-tls-secret
# enableDarkFeatures is used to enable or disable REST endpoints depending on the env. we are deploying to
# there are some REST endpoints we only want enabled in a development environment. The value ends up
# in the jvm.options file the liberty server
enableDarkFeatures: REPLACEDBYOVERRIDE