#
# (C) Copyright IBM Corp. 2021, 2021
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# common  #
# ------- #
annotations:
  TOOLCHAIN_ID: null
  GIT_URL: null
  GIT_BRANCH: null
  GIT_COMMIT: null
  USER_NAME: null
  APPLICATION_VERSION: null

image:
  repository: <helm-repo>
  tag: <helm-tag>
#  pullSecret: regsecret
  #changed based on instructions in https://github.ibm.com/whc-toolchain/whc-commons/blob/stable-3.3.2/docs/ready/common-services-integration.md#access
  #didn't hardcode it in deployment.yaml, because it caused an error/warning in the toolchain insights console
  pullsecret: ibmcloud-toolchain-common-services-registry
  pullPolicy: IfNotPresent

# cohort service  #
# --------------- #
cohort:
  # Should have at least 3 replicas so that they can be spread to different
  # zones and so that during upgrades, k8s can ensure at least 1 replica is running
  # while the others are being upgraded
  replicaCount: 3
  image:
    name: cohorting-app

  service:
    type: ClusterIP
    externalPort: 9443
    ports:
      - 9080
      - 9443

  #overriden in config repo
  internalTlsCertSecretName: cohort-services-cohort-cohort-tls

  # enableDarkFeatures is used to enable or disable REST endpoints depending on the env. we are deploying to
  # there are some REST endpoints we only want enabled in a development environment. The value ends up
  # in the jvm.options file the liberty server. Set to "all" "none" (no quotes) 
  # or the specific feature value you want to enable
  enableDarkFeatures: none
  
  libertyInitialHeapSize: 1G
  libertyMaxHeapSize: 2G

# spark history server  #
# --------------------- #
sparkHistoryServer:
  enabled: true
  replicaCount: 1
  
  image:
    name: spark-history-server
  
  service:
    type: ClusterIP
    port:
      number: 18080
      name: http-historyport
  
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  
  s3:
    secret:
      name: spark-cos-secret
      accessKeyId: access-key
      secretKeyId: secret-key
    endpointId: "https://s3.us.cloud-object-storage.appdomain.cloud"
    bucket: cohort-spark-history
    eventsDir: "/"
  
# The spark.history.fs.cleaner.* options control
# how often the spark history server cleans up old event logs.
# See https://spark.apache.org/docs/latest/monitoring.html#spark-history-server-configuration-options
# for more information
  logs:
    sparkHistoryOpts: >
      -Dspark.history.fs.cleaner.enabled=true
      -Dspark.history.fs.cleaner.interval=1d
      -Dspark.history.fs.cleaner.maxAge=120d
      -Dspark.history.fs.cleaner.maxNum=Int.MaxValue
