#
# (C) Copyright IBM Corp. 2021, 2021
#
# SPDX-License-Identifier: Apache-2.0
#
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Should have at least 3 replicas so that they can be spread to different
# zones and so that during upgrades, k8s can ensure at least 1 replica is running
# while the others are being upgraded
replicaCount: 3
annotations:
  TOOLCHAIN_ID: null
  GIT_URL: null
  GIT_BRANCH: null
  GIT_COMMIT: null
  USER_NAME: null
  APPLICATION_VERSION: null

image:
  repository: <helm-repo>
  tag: <helm-tag>
#  pullSecret: regsecret
  #changed based on instructions in https://github.ibm.com/whc-toolchain/whc-commons/blob/stable-3.3.2/docs/ready/common-services-integration.md#access
  #didn't hardcode it in deployment.yaml, because it caused an error/warning in the toolchain insights console
  pullsecret: ibmcloud-toolchain-common-services-registry
  pullPolicy: IfNotPresent
  imageName: cohort-app

service:
  type: ClusterIP
  externalPort: 9443
  ports:
    - 9080
    - 9443

#overriden in config repo
internalTlsCertSecretName: cohort-services-cohort-cohort-tls

# enableDarkFeatures is used to enable or disable REST endpoints depending on the env. we are deploying to
# there are some REST endpoints we only want enabled in a development environment. The value ends up
# in the jvm.options file the liberty server. Set to "all" "none" (no quotes) 
# or the specific feature value you want to enable
#overriden in config repo
enableDarkFeatures: none

libertyInitialHeapSize: 1G
libertyMaxHeapSize: 2G