apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    worker-type: spark
  tolerations:
  - key: "autoscale"
    operator: "Exists"
    effect: "NoExecute"
  initContainers:
    - name: init
      image: registry.access.redhat.com/ubi8
      command: ['sh', '-c', 'until getent hosts kubernetes.default.svc.cluster.local; do echo waiting for kubernetes.default; sleep 2; done;']
