# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-03-12T22:07:17Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.measures_api import MeasuresApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMeasuresApi(unittest.TestCase):
    """MeasuresApi unit test stubs"""

    def setUp(self):
        self.api = MeasuresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_evaluation(self):
        """Test case for delete_evaluation

        Deletes a measure evaluation job  # noqa: E501
        """
        pass

    def test_evaluate_measures(self):
        """Test case for evaluate_measures

        Initiates evaluation of measures for given patients  # noqa: E501
        """
        pass

    def test_get_evaluate_measures_results(self):
        """Test case for get_evaluate_measures_results

        Measure evaluation job results  # noqa: E501
        """
        pass

    def test_get_evaluate_measures_status(self):
        """Test case for get_evaluate_measures_status

        Measure evaluation job status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
