# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-03-12T22:07:17Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.measure_parameter_info import MeasureParameterInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestMeasureParameterInfo(unittest.TestCase):
    """MeasureParameterInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasureParameterInfo(self):
        """Test MeasureParameterInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.measure_parameter_info.MeasureParameterInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
