# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-07-22T12:47:28Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_status import ServiceStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceStatus(unittest.TestCase):
    """ServiceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceStatus(self):
        """Test ServiceStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_status.ServiceStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
