# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-04-26T16:43:57Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.service_error import ServiceError  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceError(unittest.TestCase):
    """ServiceError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServiceError(self):
        """Test ServiceError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.service_error.ServiceError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
