# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-03-12T22:07:17Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MeasureParameterInfoList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'measure_parameter_info_list': 'list[MeasureParameterInfo]'
    }

    attribute_map = {
        'measure_parameter_info_list': 'MeasureParameterInfoList'
    }

    def __init__(self, measure_parameter_info_list=None):  # noqa: E501
        """MeasureParameterInfoList - a model defined in Swagger"""  # noqa: E501
        self._measure_parameter_info_list = None
        self.discriminator = None
        self.measure_parameter_info_list = measure_parameter_info_list

    @property
    def measure_parameter_info_list(self):
        """Gets the measure_parameter_info_list of this MeasureParameterInfoList.  # noqa: E501

        A list of parameter information objects for libraried referenced by the input measure  # noqa: E501

        :return: The measure_parameter_info_list of this MeasureParameterInfoList.  # noqa: E501
        :rtype: list[MeasureParameterInfo]
        """
        return self._measure_parameter_info_list

    @measure_parameter_info_list.setter
    def measure_parameter_info_list(self, measure_parameter_info_list):
        """Sets the measure_parameter_info_list of this MeasureParameterInfoList.

        A list of parameter information objects for libraried referenced by the input measure  # noqa: E501

        :param measure_parameter_info_list: The measure_parameter_info_list of this MeasureParameterInfoList.  # noqa: E501
        :type: list[MeasureParameterInfo]
        """
        if measure_parameter_info_list is None:
            raise ValueError("Invalid value for `measure_parameter_info_list`, must not be `None`")  # noqa: E501

        self._measure_parameter_info_list = measure_parameter_info_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MeasureParameterInfoList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MeasureParameterInfoList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
