# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-03-12T22:07:17Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PatientMeasureEvaluations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'patient_ids': 'list[str]',
        'versioned_measures': 'list[VersionedMeasures]'
    }

    attribute_map = {
        'patient_ids': 'patientIds',
        'versioned_measures': 'versionedMeasures'
    }

    def __init__(self, patient_ids=None, versioned_measures=None):  # noqa: E501
        """PatientMeasureEvaluations - a model defined in Swagger"""  # noqa: E501
        self._patient_ids = None
        self._versioned_measures = None
        self.discriminator = None
        if patient_ids is not None:
            self.patient_ids = patient_ids
        self.versioned_measures = versioned_measures

    @property
    def patient_ids(self):
        """Gets the patient_ids of this PatientMeasureEvaluations.  # noqa: E501

        List of patient identifiers used to designate a specific patient to evaluate one or more measures against  # noqa: E501

        :return: The patient_ids of this PatientMeasureEvaluations.  # noqa: E501
        :rtype: list[str]
        """
        return self._patient_ids

    @patient_ids.setter
    def patient_ids(self, patient_ids):
        """Sets the patient_ids of this PatientMeasureEvaluations.

        List of patient identifiers used to designate a specific patient to evaluate one or more measures against  # noqa: E501

        :param patient_ids: The patient_ids of this PatientMeasureEvaluations.  # noqa: E501
        :type: list[str]
        """

        self._patient_ids = patient_ids

    @property
    def versioned_measures(self):
        """Gets the versioned_measures of this PatientMeasureEvaluations.  # noqa: E501


        :return: The versioned_measures of this PatientMeasureEvaluations.  # noqa: E501
        :rtype: list[VersionedMeasures]
        """
        return self._versioned_measures

    @versioned_measures.setter
    def versioned_measures(self, versioned_measures):
        """Sets the versioned_measures of this PatientMeasureEvaluations.


        :param versioned_measures: The versioned_measures of this PatientMeasureEvaluations.  # noqa: E501
        :type: list[VersionedMeasures]
        """
        if versioned_measures is None:
            raise ValueError("Invalid value for `versioned_measures`, must not be `None`")  # noqa: E501

        self._versioned_measures = versioned_measures

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PatientMeasureEvaluations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatientMeasureEvaluations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
