# coding: utf-8

"""
    IBM Cohort Engine

    Service to evaluate cohorts and measures  # noqa: E501

    OpenAPI spec version: 0.0.1 2021-07-22T12:47:28Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ServiceErrorList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'errors': 'list[ServiceError]',
        'trace': 'str',
        'status_code': 'int'
    }

    attribute_map = {
        'errors': 'errors',
        'trace': 'trace',
        'status_code': 'statusCode'
    }

    def __init__(self, errors=None, trace=None, status_code=None, _configuration=None):  # noqa: E501
        """ServiceErrorList - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._errors = None
        self._trace = None
        self._status_code = None
        self.discriminator = None

        if errors is not None:
            self.errors = errors
        if trace is not None:
            self.trace = trace
        if status_code is not None:
            self.status_code = status_code

    @property
    def errors(self):
        """Gets the errors of this ServiceErrorList.  # noqa: E501

        Errors  # noqa: E501

        :return: The errors of this ServiceErrorList.  # noqa: E501
        :rtype: list[ServiceError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this ServiceErrorList.

        Errors  # noqa: E501

        :param errors: The errors of this ServiceErrorList.  # noqa: E501
        :type: list[ServiceError]
        """

        self._errors = errors

    @property
    def trace(self):
        """Gets the trace of this ServiceErrorList.  # noqa: E501

        error message correlation identifier  # noqa: E501

        :return: The trace of this ServiceErrorList.  # noqa: E501
        :rtype: str
        """
        return self._trace

    @trace.setter
    def trace(self, trace):
        """Sets the trace of this ServiceErrorList.

        error message correlation identifier  # noqa: E501

        :param trace: The trace of this ServiceErrorList.  # noqa: E501
        :type: str
        """

        self._trace = trace

    @property
    def status_code(self):
        """Gets the status_code of this ServiceErrorList.  # noqa: E501

        response code  # noqa: E501

        :return: The status_code of this ServiceErrorList.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this ServiceErrorList.

        response code  # noqa: E501

        :param status_code: The status_code of this ServiceErrorList.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServiceErrorList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServiceErrorList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServiceErrorList):
            return True

        return self.to_dict() != other.to_dict()
